---
- name: Install git
  apt: name=git state=latest

- name: Install Golang
  apt: name=golang state=latest

- name: Clone goapp-api
  git:
   repo: https://github.com/Hitman95/goapp-api.git
   dest: /srv/goapp-api
   clone: yes

- name: Install goapp-api service
  template: src=goapp-api.service.j2 dest=/etc/systemd/system/goapp-api.service owner=root group=root
  notify: start goapp-api

