---
- name: Install git
  apt: name=git state=latest

- name: Clone goapp-web
  git:
   repo: https://github.com/Hitman95/goapp-web.git
   dest: /srv/goapp-web
   clone: yes

- name: Install http site config
  template: src=http.j2 dest=/etc/nginx/sites-available/http owner=root group=root mode=0644
  notify: restart nginx

- name: Create link http site
  file: src=/etc/nginx/sites-available/http dest=/etc/nginx/sites-enabled/http state=link owner=root group=root mode=0644
  notify: restart nginx

